trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '70504df6-29ad-4b8d-be5e-6360c3ca8492'
  imageRepository: 'ilaymorapiirostorymaker'
  containerRegistry: 'aidevelopmentregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  aciResourceGroup: 'ai_development'
  aciName: 'storymaker'
  azureResourceManagerConnection: 'azureResourceManagerConnection'
  acrUsername: 'mor.ilay@post.runi.ac.il'


stages:
- stage: BuildAndPush
  displayName: 'Build and Push Image'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        cache: true

- stage: RunOnACI
  displayName: 'Run on Azure Container Instance'
  dependsOn: BuildAndPush
  condition: succeeded()
  jobs:
  - deployment: DeployToACI
    displayName: 'Deploy to ACI'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Run Image on ACI'
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az container create \
                  --resource-group $(aciResourceGroup) \
                  --name $(aciName) \
                  --image $(containerRegistry)/$(imageRepository):$(tag) \
                  --dns-name-label $(aciName)-dns \
                  --ports 80 443 \
                  --registry-username $(acrUsername)

